baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site

# copyright: "Ari Safari Belajar Hugo"

params:
  footer: "Customize Footer from config.yaml"

markup:
  goldmark:
    renderer:
      unsafe: true   # set true to make enable html in markdown